name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10.8
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            moodle-branch: MOODLE_403_STABLE
            database: pgsql

    steps:
      - name: Clean workspace for matrix job
        run: |
          MATRIX_ID="${{ matrix.php }}-${{ matrix.database }}-${{ matrix.moodle-branch }}"
          rm -rf "$GITHUB_WORKSPACE"
          mkdir -p "$GITHUB_WORKSPACE/matrix-$MATRIX_ID"
          echo "MATRIX_DIR=matrix-$MATRIX_ID" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: ${{ env.MATRIX_DIR }}/plugin

      - name: Fix permissions and prepare PHP
        run: |
          # Create directories if they don't exist
          sudo mkdir -p /root/.nvm/versions/node/v20.14.0/bin/
          sudo mkdir -p /root/bin
          
          # Create a PHP setup helper script
          sudo tee /tmp/php-setup-helper.sh > /dev/null << 'EOF'
          #!/bin/bash
          # This script helps setup-php action by returning success
          # and setting the correct PHP version
          
          # Get PHP version from environment
          PHP_VERSION="${PHP_VERSION:-8.2}"
          
          # Set the PHP version using update-alternatives
          sudo update-alternatives --set php /usr/bin/php${PHP_VERSION}
          
          # Always return success
          exit 0
          EOF
          
          # Make it executable
          sudo chmod +x /tmp/php-setup-helper.sh
          
          # Create symbolic links to our helper
          sudo ln -sf /tmp/php-setup-helper.sh /root/.nvm/versions/node/v20.14.0/bin/bash
          sudo ln -sf /tmp/php-setup-helper.sh /root/bin/bash
          
          # Set permissions
          sudo chmod 755 /root/.nvm/versions/node/v20.14.0/bin/bash
          sudo chmod 755 /root/bin/bash
          
          echo "PHP versions available: "
          ls -la /usr/bin/php*

      - name: Set PHP Version
        run: |
          # Set PHP version via environment variable for our helper script
          echo "PHP_VERSION=${{ matrix.php }}" >> $GITHUB_ENV
          # Also set it directly using update-alternatives
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          # Verify the selected PHP version
          php -v
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none


      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          # Install nvm v0.39.7 (temp workaround for issue moodlehq/moodle-plugin-ci#309).
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - name: Install moodle-plugin-ci
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        run: |
          moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-local_wunderbyte_table
          moodle-plugin-ci add-plugin --branch master Wunderbyte-GmbH/moodle-mod_adele
          moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-local_catquiz
          moodle-plugin-ci add-plugin --branch catmodel_main Wunderbyte-GmbH/moodle-mod_adaptivequiz
          moodle-plugin-ci add-plugin --branch main Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          MUSTACHE_IGNORE_NAMES: ''

      - name: PHP Lint
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Moodle PHPDoc Checker
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can specify the version of Node.js you are using

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        run: |
          cd vue3
          npm install

      - name: Run tests
        working-directory: ${{ github.workspace }}/${{ env.MATRIX_DIR }}
        run: |
          cd vue3
          npm test -- --ci --coverage

      - name: Clean Docker
        if: always()
        run: |
          docker container prune -f
          docker image prune -a -f
          docker volume prune -f